# Generated by Django 2.1.7 on 2019-03-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='idadade_minima',
            new_name='idade_minima',
        ),
    ]
